### ISSUE TITLE
Navigating to a non-existent URL with no defaultLocale defined throws a TypeError

### ISSUE THREAD

**Issue by x42y** [nuxt-community/nuxt-i18n#9] opened 2018-01-23 18:47 UTC
I'm trying to create a website with all content shown at `example.com/en` (or /fr, /es, /it etc.) So basically when you go to example.com, I want to redirect to /en /fr /es.. based on certain parameters, such as cookies and the browser locale.

While trying to figure out a way to do this, the first step was skipping defining a `defaultLocale`. That way, all my languages are under their respective /locale/ url (it is also necessary to include the trailing slash, otherwise you get the error shown below).

However, when navigating to a non-existent URL without a `defaultLocale`, you get:
```
{ TypeError: Cannot set property 'error' of undefined
    at Object.error (.nuxt/index.js:91:0)
    at module.exports.__webpack_exports__.a (.nuxt/i18n.plugin.js:20:0)
    at createApp (.nuxt/index.js:159:0)
    at <anonymous> statusCode: 500, name: 'TypeError' }
```

Instead of the usual `404 not found` that you get with `defaultLocale` defined.

So what I'm asking is more or less; is this expected behaviour? Are you supposed to **always** use a `defaultLocale`? And do you have any suggestion as to how I can achieve what I am trying to achieve?

Ps. Thank you for a truly superb module, the `localePath()` feature has helped me loads!

**Comment by paulgv** [comment] 2018-01-24 22:51
Hi @bobcat1 
I did some tests and I think the issue might be caused by some changes in Nuxt v1 stable release, I'll need more time to test this better.
The `defaultLocale` is not required but I always assumed it would be set, I wonder if the module should have more options/features to handle automatic locale selection or if it should be up to the user to create a middleware to do this.

**Comment by bobcat1** [comment] 2018-01-24 23:09
From my point of view (biased because of my use case) it would be great if it had an option that let you redirect to a specific /prefix, if `defaultLocale` is undefined. Or perhaps add an option to `defaultLocale` that if set to `true`, will also make the default language get a prefix, which it will then redirect to if someone tries to access the site without a prefix. Something like
```
defaultLocale: {
   locale: 'en',
   prefix: true
}
```
Just an idea, I don't know how much work that would take and I'd be happy with any solution as long as it's working :)

**Comment by bobcat1** [comment] 2018-01-25 11:33
Upon further consideration of my specific use case outlined above, I might be shooting myself in the foot with the redirect suggestions I gave you, since I don't necessarily want to redirect to the same prefix every single time, but rather base the redirect on certain parameters (cookies, browser locale..).

**Comment by paulgv** [comment] 2018-01-25 13:33
The way I see it, there should be a simple redirect option that would simply redirect `/` to the default locale's homepage, but it also should be possible to pass a custom handler to make further checks and redirect to a specific language.

**Comment by bobcat1** [comment] 2018-01-25 15:44
That sounds like a great idea :)

**Comment by andrade1379** [comment] 2018-01-25 18:33
@bobcat1 thank you for asking the question. I am too looking to be able to set the language based on a cookie and or locale based on a geolocation service I'm using.

I'm wondering if there was a way to run `switchLocalePath` from within a plugin therefore the language is set before any of the component/pages are rendered. Or something equivalent to that

**Comment by paulgv** [comment] 2018-01-26 12:48
@bobcat1 The TypeError issue has been fixed in Nuxt 1.2.0 https://github.com/nuxt/nuxt.js/releases/tag/v1.2.0

@andrade1379 That's currently not possible since `switchLocalePath` is declared in a Vue mixin but it would be nice to have this option! I'll think about it.

**Comment by paulgv** [comment] 2018-01-27 16:02
@bobcat1 just release v2.1.0 which comes with 2 new options `noPrefixDefaultLocale` and `redirectRootToLocale `: https://github.com/paulgv/nuxt-i18n#options
You can use these 2 options to force URL prefixes for languages as well as achieving simple redirections from `/` to a given locale. Hope it helps a little, we still need to have an option for more complex redirections but it's a start :)

**Comment by bobcat1** [comment] 2018-01-28 15:11
@paulgv Just had the chance to try it now, it works great! Thanks for the superquick updates :)

**Comment by andrade1379** [comment] 2018-02-01 20:14
@paulgv I've been playing around with getting this to update the i18n locale via a saved cookie value. I am checking if cookie exists and if not then we set cookie and pass one of the languages we support to the cookie then set the i18n locale.

I wanted to share with you guys to see if there was any improvements you think can be made. What I do see happening when I visit the site is a flash of the default language which is english then it switches to the correct language. Not the experience I was hoping for. I'd like for that setting of the `i18n.locale` to happen as earliest as possible before page render?

** My Geolocation service: **
```
// Plugin runs before instantiating the root vue.js application
export default async ({ app, store, commit }) => {

    // Only run on client-side
    if (process.server) return;

    console.log('STEP 1: PLUGIN IS RUNNING');

    if (/\blocalhost\b|\blocal\b|\bdev\b|(?:0\.){3}0/.test(window.location.hostname)) {
        store.commit('setApiURI', 'https://geoendpoint.com/api.json');
    }

    try {
        const api = await app.$axios.$get(store.state.apiURI);
        store.commit('setData', api);
    } catch (e) {
        console.error(e + ' API resources must be avilable');
    }

}
```

**My Cookie Check and set plugin:**
```
import Cookie from 'vue-cookie'

// Plugin runs before instantiating the root vue.js application
export default async ({ app, store, commit, route }) => {

    // Only run on client-side
    if (process.server) return;

    let lang = Cookie.get('iso');
    let isLocal = lang === app.i18n.defaultLocale;
    let isIndex = route.name.split('-')[0] === 'index';
    let country = store.state.geoData.country.toLowerCase();
    let locale;

    function setPath() {

        if (isLocal && isIndex) {
            return app.router.push('/');
        } else if (isLocal && !isIndex) {
            return app.router.push('/' + route.name.replace(/-\w+$/, ''));
        } else if (!isLocal && isIndex) {
            return app.router.push('/' + app.i18n.locale.replace('en', ''));
        }

        return app.router.push('/' + app.i18n.locale.replace('en', '') + '/' + route.name.replace(/-\w+$/, ''));

    };

    if (lang !== null) {

        await store.commit('setLocale', lang);
        await setPath();

    } else {

        switch (country) {
            case 'us':
                locale = 'en';
                break;

            case 'br':
                locale = 'pt';
                break;

            case 'mx':
                locale = 'es';
                break;

            default:
                locale = country;
                break;
        }

        await store.commit('setLocale', locale);
        await store.dispatch('setCookie');
        await setPath();

    }

}
```

**My Store Index.js file:**
```
import Cookie from 'vue-cookie'
import Vuex from 'vuex'

const store = () => new Vuex.Store({

    state: {
apiURI: 'https://geoendpoint.com/prod',
        locales: ['en', 'de', 'cn', 'es', 'pt'], geoData: {},
    },

    mutations: {
setApiURI(state, apiURI) {
            state.apiURI = apiURI
        },

        setLocale(state, locale) {
            if (state.locales.indexOf(locale) !== -1) {
                this.app.i18n.locale = locale;
            }
        }

    },

    actions: {
        async setCookie({store, commit}) {
            await Cookie.set('iso', this.app.i18n.locale, { expires: '1Y', path: '/' });
        }
    }

})

export default store;
```

**Comment by andrade1379** [comment] 2018-03-01 21:13
@paulgv I'm running into a situation where if someone makes a typo when typing in my site's url. for example: `http://mysite.com/jhdusbc` or anything other than a predetermined route and or a preset language like `/es, /pt, /de` the site errors out. Being that my site is a static site I was wondering how we can handle a situation like this.

**Closed** 2018-03-20 00:54 UTC
