### ISSUE TITLE
UI libraries delete page's title when TypeScript is used in project

### ISSUE THREAD

**Issue by Fir3st** [nuxt-community/nuxt-i18n#342] opened 2019-06-26 15:20 UTC
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://nuxtjs.org/examples/typescript](https://nuxtjs.org/examples/typescript)

### Steps to reproduce

1. Create nuxt project with TypeScript
2. Add any UI framework that supports notifications and messages (I've already tested AT UI, Element UI and Ant Design)
3. Add framework into the project
4. Put somewhere notification/message (like in my project, https://github.com/treevity/treevity/blob/antd-message/client/pages/login.vue)

### What is expected ?

The package should work without side effects

### What is actually happening?

When message/notification disappears, page's title is deleted

### Additional comments?

I know, it's weird, and my first thoughts were that's the problem of UI library, but I've tested 3 of them and the problem still persists. When I removed the package from modules, it worked fine. It works fine also for vanilla nuxt project (without TypeScript).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c253">#c253</a>)</em></sub></div>

**Comment by Fir3st** [comment] 2019-06-26 15:50
I found it's similar to https://github.com/nuxt-community/nuxt-i18n/issues/151, when I set `seo` to `false`, it works fine.

**Comment by kevinmarrec** [comment] 2019-07-03 14:20
@Fir3st I think it's not TypeScript related, this is more likely an issue with page meta (`vue-meta`) being overriden at some moment.

And please provide a ready reproduction repository, not something where steps are installing packages, create or moving files.

**Comment by Fir3st** [comment] 2019-07-03 15:25
@kevinmarrec Ok, I've created example repository https://github.com/Fir3st/nuxt-i18n-test with two branches: `master` and `javascript` where javascript branch is equivalent to `master` branch. When you use plain js version, it works fine, but with Typescript (even with plain js page declaration) it causes the issue. And as I wrote before, if you set `seo` to `false`, it works fine.

**Comment by rchl** [comment] 2019-07-03 20:01
@Fir3st I can confirm that typescript version has the problem while javascript doesn't but I don't know why.

That said, `seo = true` is pure evil and I'm hoping it will be disabled by default in next major version - #346

Also, while I don't know where the difference in behavior comes from, it might be fixed in latest vue-meta version, I feel. Nuxt is not using vue-meta@2 yet though, so it's hard to test.

**Comment by pimlie** [comment] 2019-07-03 20:30
Probably similar as reported here? https://github.com/nuxt/vue-meta/issues/396

Thats fixed in vue-meta v2.0.4. Although nuxt will print a warning about a not recommended version, you can ignore that. So feel free to test vue-meta v2 in your project and report any errors in the vue-meta repo. Thanks!

**Comment by kevinmarrec** [comment] 2019-07-04 07:50
@Fir3st @rchl 
Will check it out but yeah I'm confused too, TypeScript becomes JavaScript at Webpack build step (`ts-loader`), so runtime should be same in both TS & JS, really weird that there would be in a issue only with TS.

**Comment by rchl** [comment] 2019-09-02 09:10
@Fir3st I've updated your project to work with latest Nuxt (https://github.com/rchl/bugs-nuxt-i18n-typescript-title ) and it works for me there without problems now. So problem seems fixed.

**Closed by rchl** 2019-09-02 09:10 UTC
Labels: cmty:bug-report

**Comment by kevinmarrec** [comment] 2019-09-03 12:09
As a side note, AFAIK this is something that has been fixed through `vue-meta@2` that is shipped since Nuxt 2.9.
