### ISSUE TITLE
"Template src not found:" when using Electron builder

### ISSUE THREAD

**Issue by pierbettassa** [nuxt-community/nuxt-i18n#219] opened 2019-02-14 14:12 UTC
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/nuxt-community/electron-template](https://github.com/nuxt-community/electron-template)

### Steps to reproduce

Clone template repository
Install and setup nuxt-18n as described in https://github.com/nuxt-community/nuxt-i18n
Build: npm run build
Open app created in dist folder

### What is expected ?

Nuxt.js app should work inside electron like in a standard browser.

### What is actually happening?

Empty page in Electron browser, error `FATAL  Template src not found: <project_path>\dist\win-unpacked\resources\app.asar\node_modules\nuxt-i18n\src\templates\.eslintrc.js` is displayed in parent shell.

### Additional comments?

This problem is originated in `src/index.js`, line `for (const file of readdirSync(templatesPath)) {`.
The issue is caused by `readdirSync` function, see https://github.com/electron/asar/issues/103 
Workaround/solution: remove the trailing path separator from `TEMPLATES_DIR` value exported in `src/helpers/constants.js`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c204">#c204</a>)</em></sub></div>

**Comment by mithom** [comment] 2019-06-13 20:07
i have exactly the same issue

**Comment by mithom** [comment] 2019-09-03 12:37
@pierbettassa you ever found a solution for this? because this issue got silently ignored sadly enough

**Comment by rchl** [comment] 2019-09-03 19:50
I've set up an nuxt + electron + nuxt-i18n project at https://github.com/rchl/electron-nuxt-test and I can't reproduce the problem. Anyone knows why? Has never electron fixed it? That project is using electron 6.

**Comment by pierbettassa** [comment] 2019-09-03 21:12
> 
> 
> @pierbettassa you ever found a solution for this? because this issue got silently ignored sadly enough

I used a workaround in package.json script (using [(https://www.npmjs.com/package/replace-in-file)]):
`"build-ele": "npx replace-in-file 'templates/' 'templates' node_modules/nuxt-i18n/src/helpers/constants.js && nuxt build && electron-builder"`



> 
> 
> I've set up an nuxt + electron + nuxt-i18n project at https://github.com/rchl/electron-nuxt-test and I can't reproduce the problem. Anyone knows why? Has newer electron fixed it? That project is using electron 6.

Thank you for trying it. I haven't worked anymore on that project during the last four months so that that bug could have been fixed. I'll try your project asap!

**Comment by pierbettassa** [comment] 2019-09-03 21:13
[](https://www.npmjs.com/package/replace-in-file)

**Comment by pierbettassa** [comment] 2019-09-03 21:14
[](https://www.npmjs.com/package/replace-in-file)

**Comment by mithom** [comment] 2019-09-04 15:23
will try it out as well, as i currently just worked on my project without i18n, wanted to delay it untill last (which is never smart)

**Comment by mithom** [comment] 2019-09-26 09:57
well, i tried it, and it keeps happening for me.
In development there is no issue, it occurs when running in production after building

**Comment by rchl** [comment] 2019-09-26 10:21
I suppose it might be Windows-specific as I can't reproduce with my test repo above with `npm run build` on Mac.

**Comment by mithom** [comment] 2019-09-26 10:28
well i just tried updating to latest electron version 6.0.10 and i still appear to have the issue, let me check your test project for differences, can't test on mac though, don't have one

**Comment by mithom** [comment] 2019-09-26 11:05
hmmm i notice you are using a different electron-builder.
i am using https://github.com/electron-userland/electron-builder
my build script is as follows:
`"build": "nuxt build && electron-builder -p never"`

**Comment by mithom** [comment] 2019-09-26 11:12
@rchl trying out @pierbettassa 's suggested solution, I can confirm it does work
(srry for the message spam)

**Comment by mithom** [comment] 2019-09-26 12:54
not sure on how to run test cases, but made a fork with the fix:
https://github.com/mithom/nuxt-i18n

**Comment by mithom** [comment] 2019-10-02 12:08
i do not have this issue in electron 6.0.11, not sure what went wrong with electron 6.0.10, but everything is fixed with the latest version of both packages (i was also on 6.2.x instead of 6.3.0 from nuxt-i18n, which solved the issue). For me this can be closed

**Closed** 2019-12-08 12:50 UTC
Labels: bug, cmty:bug-report, wontfix
