### ISSUE TITLE
Breaks styles when using with vuetify (including <head> tag) .

### ISSUE THREAD

**Issue by lucassith** [nuxt-community/nuxt-i18n#100] opened 2018-06-15 15:04 UTC
### Version

[v4.0.0](https://github.com/nuxt-i18n/releases/tag/v4.0.0)

### Reproduction link

[https://github.com/Lucassith/vuetify-nuxt-i18n-bug](https://github.com/Lucassith/vuetify-nuxt-i18n-bug)

### Steps to reproduce

Clone the repo and run `yarn install && yarn dev`.
Open localhost:3000.
See that the button's color "fades off" with each refresh. Also you can observe that all of the page changes its style + head tag does not contain all the meta.

You can see how it should look like when you remove "nuxt-i18n" from modules (or entire modules key) in nuxt.config.js. 

### What is expected ?

Load styles properly.

### What is actually happening?

Does not load styles properly.
As an example you can observe that button "primary" with text "Test" should be green.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c93">#c93</a>)</em></sub></div>

**Comment by igalil** [comment] 2018-06-16 16:33
Hello, I have the same problem here.

The content of my `head` get replaced. But then the some tags are missing like:
- `meta` tags,
- `link` tags that contain the material icons and roboto front,
- `style` tag with `id="vuetify-theme-stylesheet"`.

If you slow down the internet speed (via Chrome) to Fast or Slow 3G, you'll see that it works fine. You can see in the Network tab that the `woff2` fonts files are loaded before the `vendor.js` and `app.js` and the whole page looks OK.

**Comment by jean-airoldie** [comment] 2018-06-18 04:14
Hi, I'm having the same issue. 

From my understanding, this is caused by the nuxt-i18n vuex module registration, but only the first time the page is rendered.

For instance, if `vuex: false` is set in the [nuxt-i18n module configuration](https://nuxt-community.github.io/nuxt-i18n/options-reference.html), then the styling loads properly. The same is also true if we remove the `index.js` from the `/store` directory.
I suspected that this was exclusive to SSR mode, which could have explained why it exclusively affects the page's initial render, but it is not the case, as the issue persists even when `mode: 'spa'` is set in the [nuxt.config.js](https://nuxtjs.org/api/configuration-mode).

**Comment by dschreij** [comment] 2018-06-18 10:11
Same problem here. Only opening the developer tools somehow solves this already, so I guess it's a race issue somewhere.

**Comment by Lucassith** [comment] 2018-06-18 10:33
Opening dev tools throws webpack error which stops script execution.

**Comment by dschreij** [comment] 2018-06-18 13:03
Setting `vuex: false` solved the issue, as @jean-airoldie suggested, but I don't know what the effect of this is on the long run. At first sight, it doesn't seem to matter much, and my app keeps working as expected.

**Comment by Lucassith** [comment] 2018-06-18 13:28
You can also use non-nuxt module version of i18n, just add 
`"vue-i18n": "^7.8.0",` to packages.json then create a plugin like this:

`import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

export default ({ app, store }) => {
  // Set i18n instance on app
  // This way we can use it in middleware and pages asyncData/fetch
  app.i18n = new VueI18n({
    locale: 'pl',
    messages:
      {
        'en': require('~/lang/en-US.json'),
        'pl': require('~/lang/pl-PL.json')
      }
  })
}`

add it to nuxt.config.js. $t will be available everywhere in your app. You can also use this instance to work with vee-validate:

`import Vue from 'vue'
import VeeValidate from 'vee-validate';
import pl from 'vee-validate/dist/locale/pl'

export default function(context) {
  pl.messages.is = function(e, i) {
    return "Pola nie są identyczne"
  }

  Vue.use(VeeValidate, {
    i18n: context.app.i18n,
    dictionary: {
      pl
    }
  })
}`

This way vee-validate will be able to get current locale from i18n itself.

**Comment by Zsavajji** [comment] 2018-06-18 14:08
Experiencing same issue, also downgrading to 3.3.1 does not solve the error.

**Comment by rhrn** [comment] 2018-06-20 19:57
It's happen after meta refresh in `vue-meta`
https://github.com/declandewet/vue-meta/blob/798d5a420cd772022cfb540a195e9aeca3b121a1/src/shared/plugin.js#L94

**Comment by gahabeen** [comment] 2018-06-27 12:05
@rhrn is on to something, it does fix the issue in my app too when settin `seo: false`.

**Comment by mapeal2** [comment] 2018-06-27 22:47
Experiencing the same issue here, with the same fixes.

**Comment by alanaasmaa** [comment] 2018-06-29 11:41
Same problem. Here and same fix `seo: false` fixes it.

I noticed the problem when my title tags were dissapearing.

**Comment by dmydry** [comment] 2018-07-14 06:20
+1 `vuex = false` solved the problem
will try to find out the reason of this effect

**Comment by klessou** [comment] 2018-07-30 09:35
Any update on this issue ?

**Comment by trylovetom** [comment] 2018-08-20 12:12
Any update on this issue ?

**Comment by kevinmarrec** [comment] 2018-10-05 17:35
Any update ?

Cause currently it doesn't seem to have a solution with Nuxt I18n SEO + Vuetify both working fine.

**Comment by haexhub** [comment] 2018-11-27 21:53
why is this issue closed? I still have this problem! seo:false solved it for the moment.

**Comment by igalil** [comment] 2018-12-10 18:22
Hello All,

`seo: false` is defenitely not a "fix" but a temporary workaround, as it disable the SEO function of nuxt-i18n.
Is there any new on this issue, anything... ?

Thanks a lot :)

**Comment by langald** [comment] 2019-01-11 11:16
same issue:
in head section are missing link tags with goggle fonts

**Comment by michaelize** [comment] 2019-01-24 04:46
In the latest version, this issue seems have been fixed. In https://github.com/nuxt-community/nuxt-i18n/pull/178 the vuex SSR bug has been fixed.

**Comment by estylehq** [comment] 2019-05-29 14:52
in my case, is not helpful ```seo: false``` and ```return this.$nuxtI18nSeo;``` in ```~/layout/default.vue:head()```

missing ```style-id:vuetify-theme-stylesheet``` and ```link alternates``` data.

* ~/layout/default.vue
```
export default {
  head() {
    return this.$nuxtI18nSeo();
  },
  components: {
    ...
  },
  data() {
    return {
      ...
    };
  },
  computed: {
    ...
  },
  methods: {
    ...
  },
};
</script>
```

* ~/lang/config.js
```
export default {
  locales: [
    {
      code: 'ko',
      iso: 'ko-KR',
      name: '한국어',
      file: 'ko-KR.js',
    },
    {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      file: 'en-US.js',
    },
  ],
  defaultLocale: 'ko',
  lazy: true,
  langDir: 'lang/',
  seo: false,
  detectBrowserLanguage: {
    useCookie: true,
    cookieKey: 'i18n_redirected',
  },
};
```

* ~/nuxt.config.js
```
import langConfig from './lang/config';
...
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    ['nuxt-i18n', langConfig],
  ],
...
```

**Comment by kevinmarrec** [comment] 2019-07-29 07:41
Can someone try with Vuetify 2 and tell me if it's still breaking ? Thanks.

**Comment by ptdev** [comment] 2019-08-06 11:10
Hi,

I'm using latest nuxt-vuetify module (which is using vuetify v2) along with nuxt-i18n and I also have this issue.
  
Setting the seo parameter to false appears to solve it.

**Comment by kevinmarrec** [comment] 2019-08-06 11:27
@ptdev Can you try with `nuxt-edge` instead of `nuxt` ? It ships `vue-meta@2` which should have fixed this issue (through https://github.com/nuxt/vue-meta/pull/373).

If it works, you will be able to use the `seo` parameter back starting Nuxt 2.9.

**Comment by ptdev** [comment] 2019-08-06 11:40
@kevinmarrec you're right.

I've just updated to nuxt-edge and can confirm that it does indeed appear to be fixed.

Thanks for the support 👍

**Comment by manniL** [comment] 2019-08-07 16:19
Awesome! Closing here then :relaxed:

**Closed by manniL** 2019-08-07 16:19 UTC
Labels: cmty:bug-report
