### ISSUE TITLE
Build error when just added nuxt-i18n to nuxt.config

### ISSUE THREAD

**Issue by tats-u** [nuxt-community/nuxt-i18n#416] opened 2019-08-26 11:02 UTC
### Version

[v6.0.2](https://github.com/nuxt-i18n/releases/tag/v6.0.2)

### Reproduction link

[https://github.com/tats-u/nuxt-ts-vuetify-i18n-test](https://github.com/tats-u/nuxt-ts-vuetify-i18n-test)

### Steps to reproduce

```
git clone https://github.com/tats-u/nuxt-ts-vuetify-i18n-test
cd nuxt-ts-vuetify-i18n-test
yarn install
yarn run dev
```

### What is expected ?

``` 
ERROR  Unexpected character '@' (10:0)                                              19:57:01  

  at _class.pp$4.raise (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:2836:15)       
  at _class.pp$9.getTokenFromCode (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:4569:10)
  at _class.pp$9.readToken (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:4297:17)   
  at _class.pp$9.nextToken (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:4288:17)   
  at _class.pp$9.next (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:4245:10)        
  at _class.pp$3.parseLiteral (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:2299:10)  at _class.pp$3.parseExprAtom (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:2210:19)
  at _class.parseExprAtom (node_modules\nuxt-i18n\node_modules\acorn-dynamic-import\lib\index.js:75:117)
  at _class.pp$1.parseImport (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:1553:55) 
  at _class.pp$1.parseStatement (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:863:49)
  at _class.parseStatement (node_modules\nuxt-i18n\node_modules\acorn-dynamic-import\lib\index.js:63:118)
  at _class.pp$1.parseTopLevel (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:746:23)  at _class.parse (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:553:17)
  at Function.parse (node_modules\nuxt-i18n\node_modules\acorn\dist\acorn.js:576:37)
  at _19f‍.r.exports.extractComponentOptions (node_modules\nuxt-i18n\src\helpers\components.js:
20:61)
  at buildLocalizedRoutes (node_modules\nuxt-i18n\src\helpers\routes.js:29:21)
```

### What is actually happening?

Build succeeded

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c294">#c294</a>)</em></sub></div>

**Comment by rchl** [comment] 2019-08-26 11:33
Duplicate of #408

**Closed by rchl** 2019-08-26 11:33 UTC
Labels: cmty:bug-report

**Comment by tats-u** [comment] 2019-08-26 13:51
Oh, it's true.  Should I write this report also to that issue?
