### ISSUE TITLE
Nuxt-link is not changing to localized path

### ISSUE THREAD

**Issue by janswist** [nuxt-community/nuxt-i18n#709] opened 2020-05-14 08:01 UTC
### Version
nuxt-i18n: 6.11.1
nuxt: 2.12.2

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
```
i18n: {
    lazy: true,
    langDir: 'lang/',
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en-US.js',
        flag: '🇬🇧'
      },
      {
        code: 'pl',
        name: 'Polski',
        file: 'pl-PL.js',
        flag: '🇵🇱'
      }
    ],
    defaultLocale: 'pl',
  },
}
```

### Reproduction Link

No link.

### Steps to reproduce

I have a navbar with nuxt-links like this:
```
b-nav-item.mr-4(
  :to="localePath('/profile')"
) {{ $t('navbar.profile') }}
```
(_yes, `navbar.profile` translation works as expected_)
and a component `/profile` with this:
```
export default {
  nuxtI18n: {
    paths: {
      en: '/profile',
      pl: '/moj-profil',
    }
  },
  ...
}
```
### What is Expected?

When:
- on default locale (`pl`) I expect `domain.com/moj-profil`
- when on `en` locale then `domain.com/en/profile`.

### What is actually happening?

- On `pl` locale I get: `domain.com/profile` and error page not found when clicked (but when I manually input `/moj-profile` then I can access the page so that part in component seems to work). Should be `domain.com/moj-profil`
- on `en` I get `domain.com/en/profile` and clicked this works

**Comment by rchl** [comment] 2020-05-14 08:07
Duplicate of #641

It might work when referring to route by `name` rather than `path` but probably it won't given what I said in #641.

**Closed by rchl** 2020-05-14 08:07 UTC
Labels: bug

**Comment by janswist** [comment] 2020-05-14 08:24
Then what's the point of this section: https://nuxt-community.github.io/nuxt-i18n/routing.html#in-component-options

If we can create localized paths in-component then I suppose it's natural that we also want to access them via those links. So what is the solution for that? Give my routes name?

**Comment by rchl** [comment] 2020-05-14 09:15
Actually it works when using route name. You can check it out here: https://codesandbox.io/s/i18n-plugin-i18nlocales-ouwhn?file=/pages/index.vue

Every route has a name. You can see them in generated files in `.nuxt/route.js`. You can pass those to `localePath`. It's preferred anyway as passing paths is not gonna work in all cases (for example this case or dynamic paths).

**Comment by janswist** [comment] 2020-05-14 09:24
> Actually it works when using route name. You can check it out here: https://codesandbox.io/s/i18n-plugin-i18nlocales-ouwhn?file=/pages/index.vue
> 
> Every route has a name. You can see them in generated files in `.nuxt/route.js`. You can pass those to `localePath`. It's preferred anyway as passing paths is not gonna work in all cases (for example this case or dynamic paths).

Thanks! That worked - haven't seen `.nuxt/router.js` before.

**Comment by janswist** [comment] 2020-05-14 09:35
One more thing (for others): when adding `localePath()` to your `nuxt-link` you have to restart the whole server. Seems like it's not supported by hot reload and it might save you some headaches.

**Comment by Energon7** [comment] 2021-03-04 13:19
fix here: https://github.com/nuxt-community/i18n-module/pull/1088
