### ISSUE TITLE
Index page with dynamic routes corrupt path on any non-default locale with prefix

### ISSUE THREAD

**Issue by Snitovets** [nuxt-community/nuxt-i18n#463] opened 2019-09-25 09:07 UTC
### Version

[6.2.1](https://github.com/nuxt-i18n/releases/tag/6.2.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-y9vve?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-y9vve?fontsize=14)

### Steps to reproduce

Trying to use dynamic routes on index page to apply single page for signin and signup. Just want to provide $route.params.id to <nuxt-child> and show user specific data. But path mess up on page reload. Also working well on nested routes like '/about/:id'.

### What is expected ?

clean path on index page reload like /ru or /en

### What is actually happening?

/ru/ru or /en/en

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c308">#c308</a>)</em></sub></div>

**Comment by rchl** [comment] 2019-09-25 22:16
I can't seem to reproduce any issue on codesandbox, but since you are using brower detection, it could be specific to your browser configuration. Can you show your browser's language configuration? For example,
![Screenshot 2019-09-26 at 00 15 55](https://user-images.githubusercontent.com/153197/65643763-e21ad600-dff2-11e9-9476-0832f398cf98.png)
 mine looks like this:

**Comment by Snitovets** [comment] 2019-09-26 06:44
In your case the result must be:
![image](https://user-images.githubusercontent.com/38501107/65664285-b115c200-e041-11e9-90ba-9542541de9cd.png)

also fallback option is english.

my config:
![image](https://user-images.githubusercontent.com/38501107/65664455-07830080-e042-11e9-8c36-cadc580b5a7d.png)

**Comment by rchl** [comment] 2019-09-26 06:49
I don't see that.
I think it could happen if your browser is blocking cookies (Adblock, some privacy tools, browser settings)

**Comment by Snitovets** [comment] 2019-09-26 07:31
I have same issue in any browsers :(
I thought it's because of dynamic path on index page.

**Comment by Snitovets** [comment] 2019-09-26 07:38
I tried on all my devices, and have same issue
Try these steps:
1. go to about page;
2. go back to index;
your path should be /en/
3. reload page few times

**Comment by rchl** [comment] 2019-09-26 07:41
Yes, I can see it now.

**Comment by rchl** [comment] 2019-09-26 08:30
You are affected by issue #152. You can work around it by moving your default locale to last position:
```js
        locales: [
          { code: "ru", name: "RU", iso: "ru_RU", file: "ru_RU.js" },
          { code: "en", name: "EN", iso: "en_US", file: "en_US.js" },
          { code: "uk", name: "UA", iso: "uk_UA", file: "uk_UA.js" },
        ],
```

**Comment by Snitovets** [comment] 2019-09-26 08:47
Thank you, now it's working as expected!

**Comment by rchl** [comment] 2019-10-21 20:19
Duplicate of #152.

**Closed by rchl** 2019-10-21 20:19 UTC
Labels: cmty:bug-report
