### ISSUE TITLE
nuxt-link does not work in transition-group

### ISSUE THREAD

**Issue by alexkcollier** [nuxt-community/nuxt-i18n#73] opened 2018-04-17 15:43 UTC
### Reproduction link

[https://github.com/nuxt-community/nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n)

### Steps to reproduce

1. Install nuxt
2. Install and configure nuxt-i18n
3. Place nuxt-link in transition group with or without localePath()

nuxt.config.js
```js
module.exports = {
  mode: 'universal',
  modules: [
    ['nuxt-i18n', {
      locales: [
        { code: 'en' },
        { code: 'fr' },
        { code: 'es' }
      ],
      defaultLocale: 'en',
      vueI18n: {
        fallbackLocale: 'en',
        messages: {
          en: {
            welcome: 'Welcome'
          },
          fr: {
            welcome: 'Bienvenue'
          },
          es: {
            welcome: 'Bienvenido'
          }
        }
      }
    }]
  ]
}
```

index.vue
```vue
<template>
  <div>
    <transition-group>
      <nuxt-link
        v-for="i in 3"
        :key="i"
        to="/new">
      New
      </nuxt-link>
    </transition-group>
  </div>
</template>
```
![error.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/fa55a3d0-4255-11e8-b6c5-17d974211996.png)

### What is expected ?

Route transition

### What is actually happening?

children is undefined

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c66">#c66</a>)</em></sub></div>

**Comment by paulgv** [comment] 2018-04-17 16:09
Hi @alexkcollier 
I'm currently unable to reproduce the issue on a fresh install. What versions of Nuxt and nuxt-i18n are you using? What's in your pages directory?
It would really help if you could provide a sample project with the issue.
At first glance, I'm not sure this has anything to do with `<transition-group>` and I don't see how it could be related to nuxt-i18n either, so I'll need more details on this!

Thanks!

**Comment by alexkcollier** [comment] 2018-04-17 16:57
I've tested with nuxt 1.0.0 and 1.4.0 with nuxt-i18n 2.9.2 and 2.9.4. 

My pages directory contains index.vue, new.vue and README.md. This is in a fresh instance of nuxt created through `npx create-nuxt-app .` with no extra packages other than nuxt-i18n.

I tried running with `npm run dev` and `npm start`, and the issue only occured in dev. The issue also only occurs when nuxt-i18n is loading in nuxt.config.js. When nuxt-i18n is loaded, I can only use `<a>` for links in transition groups. When it isn't, I can use `nuxt-link` as well.

**Comment by paulgv** [comment] 2018-04-19 13:13
@alexkcollier I invited you to collaborate to this repo: https://github.com/paulgv/nuxt-i18n-transition-group-issue
I've tried reproducing your issue there but everything works fine so maybe you'll manage to do it so I can have a look afterward.

Thanks!

**Comment by alexkcollier** [comment] 2018-04-19 13:55
I've reproduced with your repo as well, but I've also managed to get it to stop reproducing in all instances on my main computer.

Stack trace pointed me here in .nuxt/client.js:
```js
  // line 521
  if (process.env.NODE_ENV !== 'production') {
    console.error(err);
  } else {
    console.error(err.message || nuxtError.message);
  }
```
So I went back to my original repo which is using cross-env, built and ran in production. Everything worked as intended, no errors, in my repo and your repo. Switched to dev with cross-env and I've had no issues with `nuxt-link` in `transition-group` in any repo.

On a fresh computer without cross-env, however, the issue is reproducing with your repo, both in dev and production. Both computers are on Windows 10, npm 5.7.1, Node 9.8 on the main and 8.9 on the other.

**Comment by alexkcollier** [comment] 2018-04-19 13:58
I left it running in the background on my computer while replying, went back and tried the links, and the issue occurred again.

**Comment by Jesus82** [comment] 2018-07-29 15:42
I have the same issue. It happens when I click a  `nuxt-link`, and in the origin page there is a `transition-group` with a `component` inside. Target page then appears with the `children is undefined` error.

In my case, the `nuxt-link` is outside of the `transition-group`.

**Comment by junkboy0315** [comment] 2018-10-16 23:51
same issue.

component (not normal element) inside `transition-group` occurs following errors related to `transition-group`.
This error doesn't happen without nuxt-i18n.

<img width="707" alt="default" src="https://user-images.githubusercontent.com/10986861/47053642-f4886f00-d1e8-11e8-8a06-bd400a9fa2e8.PNG">

**Comment by Harry7Lee** [comment] 2018-10-23 04:18
I have the same problem too.
If put any `<nuxt-link :to='localePath()'></nuxt-link>` inside the <transition-group>, it will return error.
nuxt-link with localePath() is fine.

**Comment by rchl** [comment] 2018-11-15 10:15
I've reported this as https://github.com/nuxt/nuxt.js/issues/4319 in nuxt.js before finding this bug. It has link to reproducible testcase.

**Comment by arantes555** [comment] 2019-01-30 16:02
Seeing the same issue here. In `dev` only, `nuxt-link` inside a `transition-group` with `nuxt-i18n` enabled gives the error. Removing any of those 4 makes it work fine.

**Comment by rchl** [comment] 2019-05-09 10:40
Can't reproduce it anymore myself. Even with old tests.

**Comment by paulgv** [comment] 2019-05-09 22:36
Closing for now!

**Closed by paulgv** 2019-05-09 22:36 UTC
Labels: cmty:bug-report
